---
title: "Note de synthèse sur les Series Chronologiques"
author: Hissein Tidei^[[Twitter](https://twitter.com/HisseinTidei)]
twitter: 
  username: Hissein_Tidei
  site: twitter
output:
  pdf_document: 
    number_sections: yes
  # github_document: default
  toc: yes
  highlight: monochrome
  fig_caption: yes
  number_sections: yes
  #md_document: default
date: "2023-05-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Nature des series 

## Concepts de Base
> **Qu'est ce qu'une série chronologique ou Time Series (TS)?**

 C'est une suite finie des observations effectuer à un intervalle régulier au cours du temps. Dite aussi série temporelles, elle se matérialise économiquement par l'observation des grandeurs telles que: IPC, PNB, PIB, etc.
 
> **La notion de processus stationnaire au sens large (SSL) d'une TS :**

Un processus est $X_t$ est SSL, au sens faible, ou dite de "second ordre" si et seulement si: 

1. $\mathbb{E}(X_t)=\mu$: constant ou ne croit pas avec le temps ($t$): \textcolor{red}{démunie de tendance};
2.  $\mathbb{E}(X^{2}_t)=Var(X_t)=\sigma^2 \neq \infty$: c'est dire \textcolor{red}{constant} et ne tend pas vers l'infinie au fil du temps  \textcolor{red}{infinie au fil du temps};
3. $\gamma\left(k\right)$, sa fonction d'auto-covariance , est dépendante de \textcolor{red}{l'ampleur du décalage} $k$ et non de la position en $t$, celle-ci étant: 
   *  $\gamma \left( k \right) = Cov \left( X_t, X_{t+k}\right)=E\left\lbrace \left(X_t-\mathbb{E}\left(X_t\right)\right) \left(X_{t+k}-\mathbb{E}\left(X_{t+k}\right) \right)\right\rbrace$ $\;\forall k \in \mathbb{Z}$ 
   *  $\gamma\left(k=0\right)=\gamma\left(0\right)=\sigma^{2}_x=Var\left(X\right)$ $=>$ confirme le respect de (2.).
   
> **La fonction  d'auto-corrélation d'un processus $X_t$ SSL**

Confondue avec la covariance dans le cadre de la stationnarité des séries chrono, elle écrit comme suit ^[Cf au démonstration]:  

 \begin{equation}
                             \rho\left(k\right)= cor \left(X_t,X_{t+k}\right) = \frac{Cov \left( X_t, X_{t+k}\right)}{Var\left(X_t\right)Var\left(X_{t+k}\right)} \Longrightarrow \frac{\gamma\left(k\right)}{\gamma\left(0\right)} 
 \end{equation} . 
 
 
> **Bruit blanc (BB) ou White noise**
  
  a- ***Simple BB***: 
   
   $X_t \rightsquigarrow BB\left(0,\sigma^2\right)$  si : 
   
   * $\mathbb{E}\left(X_t\right)=0$;
   * $Var\left(X_t\right)=  \sigma^2$;
   * $\gamma \left( k \right) = Cov \left( X_t, X_{t+k}\right)=0 \quad \forall k  \neq  O$ $\Longrightarrow$
     - $\gamma \left( k = o \right)=\sigma^2$
     - $\gamma \left( k \neq o \right) =0$
     
NB: \textcolor{red}{Un BB est processus SSL}.

  b- ***BB Gaussien(BBG)***: 
  
  $X_t \rightsquigarrow BBG\left(0,\sigma^2\right)$  *ssi* : 
  
   * $X_t: i.i.d  \rightsquigarrow N\left(0,\sigma^2\right)$ 
  
Attention : si $X_t\rightsquigarrow BB\left(0,\sigma^2\right)$ $\longrightarrow$ $\rho\left(k\right)= \frac{\gamma\left(k\right)}{ \gamma\left(0\right)}$
  
  
## Un processsus moyen Mobile  d'ordre q: MA(q)

### Un MA(q=1):
 
 
$MA(1)$ est un processus $X_t$, tel que : 
  
\begin{equation}
X_t= \mu + a_t + \theta a_{t-1}    
\end{equation}

où: 

\begin{align}
 a_t\rightsquigarrow BB\left(0,\sigma^2\right) \; et \;
   \theta \in \mathbb{R}\\
  \Longrightarrow  \mathbb{E}\left(a_t\right)= 0  \; \forall t, \; Var\left(a_t\right)=\sigma^2, \; Cov\left(a_t, a_{t+k}\right)= \sigma^2\mu \; \Leftrightarrow \; \lbrace k=0\rbrace
\end{align}

avec comme: 
 
\begin{align}
\mathbb{E}\left(X_t\right)=\mu \\
 Var\left(X_t\right)=\left(1+\theta^2\right)  \sigma^2 \\
\gamma\left( k \right) = Cov \left( X_t, X_{t+k}\right)= \left\{
    \begin{array}{ll}
        \left(1+\theta^2\right)\sigma^2=Var(X_t) & \mbox{si } k =O \\
        \theta\sigma^2 & \mbox{si } K=1\\
        0 & \mbox{si } k\geqslant2
    \end{array}
\right.
\end{align}

Ainsi, tout processus   $MA(1)$ \textcolor{red}{est un SSL}. Et la fonction d'auto-corrélation (\textcolor{red}{FAC}) pour un $MA(1)$ est telle que: 

\begin{equation}
FAC= \rho\left(k\right)= Cov\left(X_t, Xt+k \right)= \left\{
    \begin{array}{ll}
     1 & \mbox{si } k =O \\
        \frac{\theta}{1+\theta}  & \mbox{si } K=1\\
        0 & \mbox{si } k\geqslant2
    \end{array}
\right. 
\end{equation}


### Un MA(q=2): 

Pour un tel processus la forme est la suivante: 

\begin{align}
X_t= \mu + a_t + \theta_{2}a_{t-1} + \theta_{2}a_{t-2}  \\
 \intertext{où encore}
  a_t\rightsquigarrow BB\left(0,\sigma^2\right) \; et \;
   \lbrace \theta_2 ,\theta_1 \rbrace \in \mathbb{R} \\
 \mathbb{E}\left(X_t\right)=\mu \\
 Var\left(X_t\right)=\left(1+\Sigma^{2}_{j=1}\theta^{2}_{j} \right)  \sigma^2 \; si \; 1\leqslant k\leqslant2 \\
\gamma\left( k \right) = \left\{
    \begin{array}{ll}
        \left(\theta_k + \Sigma^{2-k}_{j=1}\theta_j\theta_{k+j}\right)\sigma^2 &  \mbox{si }  1\leqslant k\leqslant2 \\
        0 & \mbox{si } k > 2
    \end{array}
\right.
\end{align}

De même tout processus   $MA(2)$ \textcolor{red}{est un SSL} et le FAC s'annule lorsque $k>2$. 

### Un MA(q):

Pour tout $q>2$, une série $X_t $ MA(q) écrit comme suit:

\begin{align}   \label{eqmaq}
X_t   &= \mu + a_t + \theta_{2}a_{t-1} + \theta_{2}a_{t-2} + \dots +\theta_q a_{t-q}\\
      &= \mu + a_t +\Sigma^{Q}_{j=1} \theta_{j}a_{t-j}
 \intertext{où encore}
  a_t\rightsquigarrow BB\left(0,\sigma^2\right) \; et \;
    \theta_j \in \mathbb{R}  \\
   \intertext{et} 
 \mathbb{E}\left(X_t\right)=\mu \\
 Var\left(X_t\right)=\left(1+\Sigma^{q}_{j=1}\theta^{2}_{j} \right)  \sigma^2 \ \\
\gamma\left( k \right) = \left\{
    \begin{array}{ll}
        \left(\theta_k + \Sigma^{q-k}_{j=1}\theta_j\theta_{k+j}\right)\sigma^2 &  \mbox{si }  1\leqslant k\leqslant q \\
        0 & \mbox{si } k > q  \label{eqmaq}
    \end{array}
\right.
\end{align}

### Sur le Plan pratique: 

En générale, la modélisation d'une série chronologique des données réelles, comprise comme obéissant un processus à moyen mobile, pour comprendre et faire de la prévision requière la compréhension de la structure de ces données. En effet, une telle compréhension passe par la détermination de l'ordre $q$, indiquant le $k$ à partir duquel l'auto-corrélation entre les différentes périodes ou temps de la série univariée s'estompe ^[Comme en \eqref{eqmaq}, pour un $k>q$, la covariance ou, peu importe ici, l'auto-corrélation au sein de la série s'annule, c-à-d qu'il n'y a plus de lien en moyen mobile depassé k temps ou période entre deux plusieurs observations d'une série temporelle.]; en d'autre terme le $q$ détermine les niveaux, en t, de relations d'interdépendances ou de liaisons temporelles au sein de la série. Globalement, ces relations sont basées  sur des composantes tendancières (trend) ou stochastiques entre deux ou plusieurs sous-séries d'un échantillon ($X_t$).  Ainsi, se pose la question , en supposant par observation que la série à des composantes tendancière et ou  stochastique, l'odre $k$ est obtenu en identifiant la periode à patir de laquel la FAC (l'auto-corrélogramme) s'annule ($\rho(k)=0$); ainsi c'est $k$ donne les valeurs des differents $q$ qui lui sont inferieurs et qui pourront modeliser la serie en $MA(q)$:  






